### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by Matthieu-ui** [sccprogrammingclub/angular-sccprogrammingclub.com#1]
More info on this project would be great! 
I am new to the programming club but would love to get started on contributing. 

<b>How does one get this project up and running? </b>
<hr>

<b>Requirements</b>
The required bits and bobs of the project (e.g. CMS, Tailwind, etc.)

<b>Project Notes</b>
Pertinent high-level information about the project

<b>Setup!!</b>

**Comment by Matthieu-ui** [comment]
## Highly recommended
### Repo settings
<li>Description
<li>URL (if appropriate)
<li>Topics
<li>Hide features not using (for example: wiki, packages)

### README
<li>Prerequisite list
<li>QuickStart guide
<li>Where to get support / ask questions
<li>Issue template
<li>QuickStart guide
<li>Where to get support / ask questions
<li>Pull Request template

### Code of conduct

### License

**Comment by sccprogrammingclub** [comment]
Hi, Matthieu!

This project uses Angular, a frontend framework developed by Google. We host our static frontend website via AWS. Once we build the project, we upload the dist folder in a S# bucket. Then, we distribute files via CloudFront. I hope this helps.

Here's a quick start that the README.md from the frontend directory has:

> This project was generated with [Angular CLI](https://github.com/angular/angular-cli) version 14.0.1.
> 
> Development server
> 
> Run ng serve for a dev server. Navigate to http://localhost:4200/. The application will automatically reload if you change any of the source files.
> 
> Code scaffolding
> 
> Run ng generate component component-name to generate a new component. You can also use ng generate directive|pipe|service|class|guard|interface|enum|module.
> 
> Build
> 
> Run ng build to build the project. The build artifacts will be stored in the dist/ directory.
> 
> Running unit tests
> 
> Run ng test to execute the unit tests via [Karma](https://karma-runner.github.io/).
> 
> Running end-to-end tests
> 
> Run ng e2e to execute the end-to-end tests via a platform of your choice. To use this command, you need to first add a package that implements end-to-end testing capabilities.
> 
> Further help
> 
> To get more help on the Angular CLI use ng help or go check out the [Angular CLI Overview and Command Reference](https://angular.io/cli) page.

I am not familiar with React, but I will be learning it surely at some point. I decided not to migrate to React, ultimately, because Angular is great for SPAs. Therefore, our website is very ideal for it. We can use React in other projects in the future or apps we can build in the club.

Yes, we need to update the main README.md file for this repository. Some help would be nice :-)

As for other technologies, we just use Angular Material (Google fonts, Google icons, styles, etc). Since Angular is developed by Google, it is quite convenient to use their stuff.

As for CSS styling, we just use plain CSS. If you'd like to use some other parties, you can suggest it in the club and come up with a design or commit changes for everyone to check out. I'm sure it would be very interesting.

We let members manage their own pages and customise it as much as they want. Maybe you could demonstrate uses of other technologies like styling or animations in your page for the rest of us to see :-)

Thanks for the suggestion in your last message. We will put things out more organised for everyone.

Best,
Fran

**Comment by Matthieu-ui** [comment]
Nice! Sounds great! This is enough information for me to put something together! You can assign me the task (or I think I can myself? :D)

**Comment by Matthieu-ui** [comment]
I've never used Angular so I'm learning something new here. Good call on keeping it. I didn't notice there was another readme in the frontend directory! I made a branch to get familiar with all of it.

**Comment by Matthieu-ui** [comment]
also to note* If I make a read me it will be very simple on just how to run the development server, incase anyone has trouble with it like I was. But a legit one further on will be nice.
